CREATE DATABASE IF NOT EXISTS granjero;

USE granjero;

CREATE TABLE IF NOT EXISTS compras (
	id INT AUTO_INCREMENT PRIMARY KEY,
    cliente VARCHAR(50) NOT NULL,
	tiempo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );