CREATE DATABASE IF NOT EXISTS granjero;

USE granjero;

CREATE TABLE compras (
	cliente VARCHAR(50) PRIMARY KEY,
    cantidad INT NOT NULL DEFAULT 0,
    tiempo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );